# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
templates:
  params:
    author-email: astynax84@gmail.com
    author-name: Aleksei Pirogov
    copyright: Aleksei Pirogov aka astynax
    github-username: astynax
